### ISSUE TITLE
It's pretty cool except..

### ISSUE THREAD

**Issue by hiroshihorie** [luisrecuenco/LRScrollingSidebarController#4]
I need to cast controllers every time for the compiler to quiet.

What's best practice in the following situation ?

``` objective-c
[self.scrollingSidebarController showMainViewController:[[UINavigationController alloc] initWithRootViewController:controller] animated:YES];
```

**Comment by luisrecuenco** [comment]
You cannot do that unfortunately. The controller is prepared to handle the following type of controllers:

typedef UIViewController<LRScrollingSidebarController> *ISSidePanelController;

That is, UIViewController subclasses conforming that very protocol. If you try to add a UINavigationController, you'll get a compiler warning (you won't get any crash as the protocol only contains an optional method).

As a workaround for this, you can create a UIViewController subclass that acts as a container/wrapper for the UINavigationController you want to add. That class conforms that protocol and this will make the compiler to quiet.
