### ISSUE TITLE
Working with NavigationControllers

### ISSUE THREAD

**Issue by carguezu** [luisrecuenco/LRScrollingSidebarController#5]
My mainVC is a NavigationController, but I can’t come back to the LeftVC from a button in the NavigationControllerChild.

I have tried both:

```
- (IBAction)menuBarButton:(UIBarButtonItem *)sender
{
    [self.scrollingSidebarController showLeftViewControllerAnimated:YES];
}
```

 and:

```
- (IBAction)menuBarButton:(UIBarButtonItem *)sender
{
    LeftMenuViewController *leftMenuVC = (LeftMenuViewController *)[self.storyboard instantiateViewControllerWithIdentifier:@"LeftMenu"];
    [self.scrollingSidebarController showLeftViewController:leftMenuVC
                                               animated:YES];
}
```

but doesn’t work for me. Can anyone help me please?

**Comment by luisrecuenco** [comment]
self.scrollingSidebarController is nil, that is why it doesn't work. The scrollingSidebarController is property set via associated objects to the left/main/right view controller. In your case, the main view controller is the navigation controller, not the child view controller pushed onto it. So, doing something like self.navigationController.scrollingSidebarController should work.

**Comment by cguerraz** [comment]
I’ve tried that, and it works now. Thank you very much, Luis! ;)
